### ISSUE TITLE
database-refactor branch mysql login errors on Cacti 1.0

### ISSUE THREAD

**Issue by fuzzbawl** [howardjones/network-weathermap#65] opened 2017-03-14 20:35 UTC
Getting the errors below. It looks like weathermap maybe isn't calling the right Cacti 1.0 function to pull DB info.

2017-03-14 14:25:22 - CMDPHP PHP ERROR WARNING Backtrace: (/poller.php: 717 api_plugin_hook)(/lib/plugins.php: 68 api_plugin_run_plugin_hook)(/lib/plugins.php: 161 weathermap_poller_bottom)(/plugins/weathermap/lib/cacti10-plugin-poller.php: 169 weathermap_run_maps)(/plugins/weathermap/lib/poller-common.php: 220 readData)(/plugins/weathermap/lib/Weathermap.class.php: 1786 readDataFromTargets)(/plugins/weathermap/lib/Weathermap.class.php: 1611 performDataCollection)(/plugins/weathermap/lib/WeatherMapDataItem.class.php: 199 collectDataFromTargets)(/plugins/weathermap/lib/WeatherMapDataItem.class.php: 237 readData)(/plugins/weathermap/lib/WMTarget.class.php: 119 ReadData)(/plugins/weathermap/lib/datasources/WeatherMapDataSource_rrd.php: 464 wmrrd_read_from_poller_output)(/plugins/weathermap/lib/datasources/WeatherMapDataSource_rrd.php: 75 mysql_real_escape_string)(CactiErrorHandler)(/lib/functions.php: 4233 cacti_debug_backtrace)

2017-03-14 14:25:22 - ERROR PHP WARNING in Plugin 'weathermap': mysql_real_escape_string(): Access denied for user 'www-data'@'localhost' (using password: NO) in file: /var/www/cacti/plugins/weathermap/lib/datasources/WeatherMapDataSource_rrd.php on line: 75

**Comment by howardjones** [comment] 2017-03-15 11:23
This is one of the parts I hadn't got to yet. It's made a bit more complicated because the rrd support shouldn't rely on Cacti (e.g. for MRTG or LibreNMS users), but poller_output support inside it obviously does.

**Comment by howardjones** [comment] 2017-03-18 19:42
This is actually a duplicate of #45.

**Closed by howardjones** 2017-03-18 19:42 UTC
