### ISSUE TITLE
Error in weathermap install Centos 7

### ISSUE THREAD

**Issue by ocalvano** [howardjones/network-weathermap#55] opened 2016-12-20 08:03 UTC
Hi

i have a error when i start weathermap :

[systemadmin@weathermap html]# ./weathermap
PHP Strict Standards:  Non-static method PEAR::isError() should not be called statically, assuming $this from incompatible context in /usr/share/pear/Console/Getopt.php on line 109

anyone know this error ?

CentOS Linux release 7.3.1611

Installed packages, channel pear.php.net:
=========================================
Package          Version State
Archive_Tar      1.3.11  stable
Console_Getopt   1.3.1   stable
PEAR             1.9.4   stable
Structures_Graph 1.0.4   stable
XML_Util         1.2.1   stable

PHP 5.4.16

regards
olivier

**Comment by howardjones** [comment] 2016-12-20 14:28
Please implement the one-line change in 1dfdf250a9776ecf713fae8032c83ca6bdae6c64

**Comment by howardjones** [comment] 2016-12-20 14:29
Duplicate of  #37

**Comment by howardjones** [comment] 2016-12-20 14:31
Sorry - this isn't a duplicate, but it IS fixed in 0.98 (which is what causes the problem for older PHP in #37). Which version are you using?

**Comment by ocalvano** [comment] 2016-12-21 04:35
Hi

i use the latest version i thinks:
php-weathermap-0.98.zip

regards

**Comment by ocalvano** [comment] 2016-12-22 05:05
I don't have the good version ?

**Closed** 2017-05-01 20:33 UTC
Labels: duplicate
